### ISSUE TITLE
Link on Osh Park

### ISSUE THREAD

**Issue by telanoc** [carlcalderon/TMC2130-Breakout-Board#1]
Hi.  Cool project, but your link on the project page on Osh Park is wrong.

It points to [https://www.oshpark.com/github.com/carlcalderon/TMC2130-Breakout-Board](https://www.oshpark.com/github.com/carlcalderon/TMC2130-Breakout-Board)

**Comment by carlcalderon** [comment]
Thank you very much. Updated the OSH Park link.
